ALTER TABLE IF EXISTS user_profiles
ADD COLUMN IF NOT EXISTS name TEXT;

ALTER TABLE IF EXISTS user_profiles
ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'user';

ALTER TABLE IF EXISTS user_profiles
ADD COLUMN IF NOT EXISTS phone TEXT;